"""
Extracted configuration service from optimizer

Automatically generated by God Object Decomposer
"""

import os
import sys
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from typing import Dict
from typing import Any


"""Get default optimization configuration."""
    def _get_default_config(self) -> Dict[str, Any]:
        """Get default optimization configuration."""
        return {
            "optimize_caching": True,
            "optimize_parallelization": True,
            "validate_improvements": True,
            "max_files_to_optimize": 500,
            "parallel_workers": min(8, psutil.cpu_count()),
            "memory_limit_mb": 200.0,
            "timeout_seconds": 300.0
        }

