// swarm-types State Machine - FSM Range 600-699
// Generated by Range-Based Eliminator

export enum swarm-typesEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface swarm-typesState {
    name: string;
    data?: any;
}

export class swarm-typesStateMachine {
    private currentState: swarm-typesState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: swarm-typesEvents, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === swarm-typesEvents.START) {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === swarm-typesEvents.COMPLETE) {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): swarm-typesState {
        return this.currentState;
    }
}
