// swarm-types State Machine - FSM Range 600-699
// Generated by Range-Based Eliminator

export enum SwarmTypesEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface SwarmTypesState {
    name: string;
    data?: any;
}

export class SwarmTypesStateMachine {
    private currentState: SwarmTypesState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: SwarmTypesEvents, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === SwarmTypesEvents.START) {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === SwarmTypesEvents.COMPLETE) {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): SwarmTypesState {
        return this.currentState;
    }
}
