// swarm-types Types - FSM Range 600-699
// Generated by Range-Based Eliminator

export interface QueenConfiguration {
readonly id: QueenId;
readonly swarmId: SwarmId;
readonly maxPrincesses: number;
readonly coordinationStrategy: CoordinationStrategy;
readonly healthCheckInterval: Duration;
readonly failoverEnabled: boolean;
readonly metaLogicEnabled: boolean;
}
export interface QueenDirective<TPayload = unknown> {
readonly id: DirectiveId;
readonly queenId: QueenId;
readonly targetDomain: PrincessDomain;
readonly targetPrincess?: PrincessId;
readonly priority: TaskPriority;
readonly payload: TPayload;
readonly deadline?: Deadline;
readonly dependencies: readonly DirectiveId[];
readonly metadata: DirectiveMetadata;
readonly createdAt: Timestamp;
}
export interface DirectiveMetadata {
readonly source: 'user' | 'system' | 'automated';
readonly complexity: ComplexityScore;
readonly estimatedDuration: Duration;
readonly resourceRequirements: ResourceRequirements;
readonly complianceLevel: ComplianceLevel;
}

export type SwarmId = string & { readonly __brand: 'SwarmId' };
export type QueenId = string & { readonly __brand: 'QueenId' };
export type PrincessId = string & { readonly __brand: 'PrincessId' };
export type DroneId = string & { readonly __brand: 'DroneId' };
export type DirectiveId = string & { readonly __brand: 'DirectiveId' };

// Range-specific type definitions for 600-699
export interface SwarmTypesConfig {
    range: '600-699';
    maxLines: number;
    decomposed: boolean;
}
