// swarm-types Facade - FSM Range 600-699
// Generated by Range-Based Eliminator

import { SwarmTypesCore } from './SwarmTypesCore';
import { SwarmTypesStateMachine } from './SwarmTypesStateMachine';

export class SwarmTypesFacade {
    private core: SwarmTypesCore;
    private fsm: SwarmTypesStateMachine;

    constructor() {
        this.core = new SwarmTypesCore();
        this.fsm = new SwarmTypesStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility
export default SwarmTypesFacade;
