// ResearchQueryProcessor Facade - FSM Range 600-699
// Generated by Range-Based Eliminator

import { ResearchQueryProcessorCore } from './ResearchQueryProcessorCore';
import { ResearchQueryProcessorStateMachine } from './ResearchQueryProcessorStateMachine';

export class ResearchQueryProcessorFacade {
    private core: ResearchQueryProcessorCore;
    private fsm: ResearchQueryProcessorStateMachine;

    constructor() {
        this.core = new ResearchQueryProcessorCore();
        this.fsm = new ResearchQueryProcessorStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility
export default ResearchQueryProcessorFacade;
