// ResearchQueryProcessor Types - FSM Range 600-699
// Generated by Range-Based Eliminator

export interface ResearchQuery {
id: string;
rawQuery: string;
intent: QueryIntent;
entities: ExtractedEntity[];
relationships: ExtractedRelationship[];
filters: QueryFilter[];
scope: QueryScope;
priority: QueryPriority;
metadata: {
timestamp: Date;
userId?: string;
sessionId?: string;
};
}
export interface QueryIntent {
primary: 'search' | 'analyze' | 'synthesize' | 'recommend' | 'trend' | 'compare';
secondary?: string[];
confidence: number;
reasoning: string;
}
export interface ExtractedEntity {
text: string;
type: 'technology' | 'company' | 'person' | 'concept' | 'method' | 'framework' | 'standard';
confidence: number;
aliases: string[];
context: string;
}

export type QueryPriority = 'low' | 'medium' | 'high' | 'urgent';


// Range-specific type definitions for 600-699
export interface ResearchQueryProcessorConfig {
    range: '600-699';
    maxLines: number;
    decomposed: boolean;
}
