// ProtocolVersionManager Facade - FSM Range 600-699
// Generated by Range-Based Eliminator

// TODO(Phase 4): Implement core module - import { ProtocolVersionManagerCore } from './ProtocolVersionManagerCore';
import { ProtocolVersionManagerStateMachine } from './ProtocolVersionManagerStateMachine';

export class ProtocolVersionManagerFacade {
    private core: ProtocolVersionManagerCore;
    private fsm: ProtocolVersionManagerStateMachine;

    constructor() {
        this.core = new ProtocolVersionManagerCore();
        this.fsm = new ProtocolVersionManagerStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility

// Backward compatibility

// Backward compatibility
export default ProtocolVersionManagerFacade;
