// ProtocolVersionManager State Machine - FSM Range 600-699
// Generated by Range-Based Eliminator

export enum ProtocolVersionManagerEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface ProtocolVersionManagerState {
    name: string;
    data?: any;
}

export class ProtocolVersionManagerStateMachine {
    private currentState: ProtocolVersionManagerState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: ProtocolVersionManagerEvents, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === ProtocolVersionManagerEvents.START) {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === ProtocolVersionManagerEvents.COMPLETE) {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): ProtocolVersionManagerState {
        return this.currentState;
    }
}
