// AutomatedDecisionEngine Facade - FSM Range 700-799
// Generated by Range-Based Eliminator

import { AutomatedDecisionEngineCore } from './AutomatedDecisionEngineCore';
import { AutomatedDecisionEngineStateMachine } from './AutomatedDecisionEngineStateMachine';

export class AutomatedDecisionEngineFacade {
    private core: AutomatedDecisionEngineCore;
    private fsm: AutomatedDecisionEngineStateMachine;

    constructor() {
        this.core = new AutomatedDecisionEngineCore();
        this.fsm = new AutomatedDecisionEngineStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility
export default AutomatedDecisionEngineFacade;
