/**
 * Type definitions for StateTransitionMonitor
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */

import { Timestamp, Milliseconds } from '~types/base/primitives';

export interface MonitoringConfig {
  enabled: boolean;
  timeout: Milliseconds;
  retries: number;
  maxConcurrency: number;
}

export interface PerformanceAlert {
  value: unknown;
}

export interface RealTimeMetrics {
  count: number;
  duration: Milliseconds;
  successRate: number;
  timestamp: Timestamp;
}

export interface StateTransitionMonitor {
  value: unknown;
}

/* AGENT FOOTER BEGIN: DO NOT EDIT ABOVE THIS LINE */
/*
 * Version & Run Log
 * Version | Timestamp | Agent/Model | Change Summary | Artifacts | Status | Notes | Cost | Hash
 * 1.0.0 | 2025-09-30T12:55:14.360294 | AutoTypeGen@Phase3 | Generated 4 type exports | ./monitoring/StateTransitionMonitor.ts | OK | Automated generation | 0.00 | e8f9ecb
 *
 * Receipt:
 * - status: OK
 * - reason_if_blocked: --
 * - run_id: auto-type-gen-e8f9ecb
 * - inputs: ["./monitoring/StateTransitionMonitor"]
 * - tools_used: ["TypeInference", "TypeGenerator"]
 * - versions: {"script":"1.0.0","nasa_rule_10":"compliant","fsm":"enum-based"}
 */
/* AGENT FOOTER END: DO NOT EDIT BELOW THIS LINE */
