// types Facade - FSM Range 600-699
// Generated by Range-Based Eliminator

import { typesCore } from './typesCore';
import { typesStateMachine } from './typesStateMachine';

export class typesFacade {
    private core: typesCore;
    private fsm: typesStateMachine;

    constructor() {
        this.core = new typesCore();
        this.fsm = new typesStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility
export default typesFacade;
