/**
 * Type definitions for primitives
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */
export interface DebugSessionId {
    value: unknown;
}
export interface Duration {
    value: unknown;
}
export interface FilePath {
    value: unknown;
}
export interface Timestamp {
    value: unknown;
}
export interface createDebugSessionId {
    value: unknown;
}
export interface createTimestamp {
    value: unknown;
}
