/**
 * Type definitions for primitives
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */

import { Timestamp, Milliseconds } from '../../src/types/base/primitives';

export interface DebugSessionId {
  value: unknown;
}

export interface Duration {
  value: unknown;
}

export interface FilePath {
  value: unknown;
}

export interface Timestamp {
  value: unknown;
}

export interface createDebugSessionId {
  value: unknown;
}

export interface createTimestamp {
  value: unknown;
}

/* AGENT FOOTER BEGIN: DO NOT EDIT ABOVE THIS LINE */
/*
 * Version & Run Log
 * Version | Timestamp | Agent/Model | Change Summary | Artifacts | Status | Notes | Cost | Hash
 * 1.0.0 | 2025-09-30T12:55:14.349324 | AutoTypeGen@Phase3 | Generated 6 type exports | ../types/base/primitives.ts | OK | Automated generation | 0.00 | b295b4f
 *
 * Receipt:
 * - status: OK
 * - reason_if_blocked: --
 * - run_id: auto-type-gen-b295b4f
 * - inputs: ["../types/base/primitives"]
 * - tools_used: ["TypeInference", "TypeGenerator"]
 * - versions: {"script":"1.0.0","nasa_rule_10":"compliant","fsm":"enum-based"}
 */
/* AGENT FOOTER END: DO NOT EDIT BELOW THIS LINE */
