# Base constants for SPEK Enhanced Development Platform

API_TIMEOUT_SECONDS = 30

# Financial constants
MINIMUM_TRADE_THRESHOLD = 0.5
MAXIMUM_FUNCTION_PARAMETERS = 10

# Analyzer constants
MAXIMUM_FUNCTION_LENGTH_LINES = 200
MAXIMUM_RETRY_ATTEMPTS = 3
MAXIMUM_NESTED_DEPTH = 5
MAXIMUM_CYCLOMATIC_COMPLEXITY = 10
MINIMUM_TEST_COVERAGE = 80
MAXIMUM_GOD_OBJECTS_ALLOWED = 25
QUALITY_GATE_MINIMUM_PASS_RATE = 0.90
DAYS_RETENTION_PERIOD = 30

# NASA POT10 Compliance Thresholds
NASA_POT10_MINIMUM_COMPLIANCE = 0.90
NASA_POT10_TARGET_COMPLIANCE_THRESHOLD = 0.92
MAXIMUM_CONNASCENCE_VIOLATIONS = 100
MINIMUM_SECURITY_SCORE = 0.95
TAKE_PROFIT_PERCENTAGE = 0.10

# Performance thresholds
MAXIMUM_RESPONSE_TIME_MS = 1000
MAXIMUM_MEMORY_USAGE_MB = 512
