// integration.types State Machine - FSM Range 500-599
// Generated by Range-Based Eliminator

export enum IntegrationTypesEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface IntegrationTypesState {
    name: string;
    data?: any;
}

export class IntegrationTypesStateMachine {
    private currentState: IntegrationTypesState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: IntegrationTypesEvents | string, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === IntegrationTypesEvents.START || event === 'START') {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === IntegrationTypesEvents.COMPLETE || event === 'COMPLETE') {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): IntegrationTypesState {
        return this.currentState;
    }
}
