// integration.types Facade - FSM Range 500-599
// Generated by Range-Based Eliminator

// TODO(Phase 4): Implement core module - import { IntegrationTypesCore } from './integration.typesCore';
import { IntegrationTypesStateMachine } from './integration.typesStateMachine';

export class IntegrationTypesFacade {
    private core: IntegrationTypesCore;
    private fsm: IntegrationTypesStateMachine;

    constructor() {
        this.core = new IntegrationTypesCore();
        this.fsm = new IntegrationTypesStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility

// Backward compatibility

// Backward compatibility
export default IntegrationTypesFacade;
