// integration.types Facade - FSM Range 500-599
// Generated by Range-Based Eliminator

import { integration.typesCore } from './integration.typesCore';
import { integration.typesStateMachine } from './integration.typesStateMachine';

export class integration.typesFacade {
    private core: integration.typesCore;
    private fsm: integration.typesStateMachine;

    constructor() {
        this.core = new integration.typesCore();
        this.fsm = new integration.typesStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility
export default integration.typesFacade;
