// MigrationPlanner State Machine - FSM Range 800-899
// Generated by Range-Based Eliminator

export enum MigrationPlannerEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface MigrationPlannerState {
    name: string;
    data?: any;
}

export class MigrationPlannerStateMachine {
    private currentState: MigrationPlannerState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: MigrationPlannerEvents, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === MigrationPlannerEvents.START) {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === MigrationPlannerEvents.COMPLETE) {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): MigrationPlannerState {
        return this.currentState;
    }
}
