// MigrationPlanner Facade - FSM Range 800-899
// Generated by Range-Based Eliminator

// TODO(Phase 4): Implement core module - import { MigrationPlannerCore } from './MigrationPlannerCore';
import { MigrationPlannerStateMachine } from './MigrationPlannerStateMachine';

export class MigrationPlannerFacade {
    private core: MigrationPlannerCore;
    private fsm: MigrationPlannerStateMachine;

    constructor() {
        this.core = new MigrationPlannerCore();
        this.fsm = new MigrationPlannerStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility

// Backward compatibility

// Backward compatibility
export default MigrationPlannerFacade;
