// pipeline-orchestrator State Machine - FSM Range 800-899
// Generated by Range-Based Eliminator

export enum PipelineOrchestratorEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface PipelineOrchestratorState {
    name: string;
    data?: any;
}

export class PipelineOrchestratorStateMachine {
    private currentState: PipelineOrchestratorState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: PipelineOrchestratorEvents, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === PipelineOrchestratorEvents.START) {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === PipelineOrchestratorEvents.COMPLETE) {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): PipelineOrchestratorState {
        return this.currentState;
    }
}
