// pipeline-orchestrator Facade - FSM Range 800-899
// Generated by Range-Based Eliminator

import { pipeline-orchestratorCore } from './pipeline-orchestratorCore';
import { pipeline-orchestratorStateMachine } from './pipeline-orchestratorStateMachine';

export class pipeline-orchestratorFacade {
    private core: pipeline-orchestratorCore;
    private fsm: pipeline-orchestratorStateMachine;

    constructor() {
        this.core = new pipeline-orchestratorCore();
        this.fsm = new pipeline-orchestratorStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility
export default pipeline-orchestratorFacade;
