// pipeline-orchestrator State Machine - FSM Range 800-899
// Generated by Range-Based Eliminator

export enum pipeline-orchestratorEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface pipeline-orchestratorState {
    name: string;
    data?: any;
}

export class pipeline-orchestratorStateMachine {
    private currentState: pipeline-orchestratorState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: pipeline-orchestratorEvents, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === pipeline-orchestratorEvents.START) {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === pipeline-orchestratorEvents.COMPLETE) {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): pipeline-orchestratorState {
        return this.currentState;
    }
}
