// pipeline-orchestrator Facade - FSM Range 800-899
// Generated by Range-Based Eliminator

import { PipelineOrchestratorCore } from './PipelineOrchestratorCore';
import { PipelineOrchestratorStateMachine } from './PipelineOrchestratorStateMachine';

export class PipelineOrchestratorFacade {
    private core: PipelineOrchestratorCore;
    private fsm: PipelineOrchestratorStateMachine;

    constructor() {
        this.core = new PipelineOrchestratorCore();
        this.fsm = new PipelineOrchestratorStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility
export default PipelineOrchestratorFacade;
