...#... ...P...e...r...f...o...r...m...a...n...c...e... ...O...p...t...i...m...i...z...a...t...i...o...n... ...C...o...n...f...i...g...u...r...a...t...i...o...n...
...#... ...P...h...a...s...e... ...2...A...:... ...R...e...s...o...u...r...c...e... ...O...p...t...i...m...i...z...a...t...i...o...n... ...S...e...t...t...i...n...g...s...
...
...#... ...R...u...n...n...e...r... ...C...o...n...f...i...g...u...r...a...t...i...o...n... ...M...a...t...r...i...x...
...r...u...n...n...e...r...s...:...
... ... ...l...i...g...h...t...:...
... ... ... ... ...t...y...p...e...:... ..."...u...b...u...n...t...u...-...l...a...t...e...s...t..."...
... ... ... ... ...c...p...u..._...c...o...r...e...s...:... ...2...
... ... ... ... ...m...e...m...o...r...y..._...g...b...:... ...7...
... ... ... ... ...m...a...x..._...t...i...m...e...o...u...t...:... ...1...5...
... ... ... ... ...s...u...i...t...a...b...l...e..._...f...o...r...:...
... ... ... ... ... ... ...-... ..."...C...a...c...h...e... ...o...p...t...i...m...i...z...a...t...i...o...n..."...
... ... ... ... ... ... ...-... ..."...S...e...l...f...-...d...o...g...f...o...o...d...i...n...g... ...a...n...a...l...y...s...i...s..."... ...
... ... ... ... ... ... ...-... ..."...L...i...g...h...t... ...v...a...l...i...d...a...t...i...o...n... ...t...a...s...k...s..."...
... ... ... ... ... ... ...
... ... ...s...t...a...n...d...a...r...d...:...
... ... ... ... ...t...y...p...e...:... ..."...u...b...u...n...t...u...-...l...a...t...e...s...t...-...4...-...c...o...r...e..."...
... ... ... ... ...c...p...u..._...c...o...r...e...s...:... ...4...
... ... ... ... ...m...e...m...o...r...y..._...g...b...:... ...1...6...
... ... ... ... ...m...a...x..._...t...i...m...e...o...u...t...:... ...3...0...
... ... ... ... ...s...u...i...t...a...b...l...e..._...f...o...r...:...
... ... ... ... ... ... ...-... ..."...C...o...n...n...a...s...c...e...n...c...e... ...a...n...a...l...y...s...i...s..."...
... ... ... ... ... ... ...-... ..."...A...r...c...h...i...t...e...c...t...u...r...e... ...a...n...a...l...y...s...i...s..."...
... ... ... ... ... ... ...-... ..."...M...E...C...E... ...d...u...p...l...i...c...a...t...i...o...n... ...a...n...a...l...y...s...i...s..."...
... ... ... ... ... ... ...-... ..."...C...o...n...s...o...l...i...d...a...t...i...o...n... ...t...a...s...k...s..."...
... ... ... ... ... ... ...
... ... ...h...e...a...v...y...:...
... ... ... ... ...t...y...p...e...:... ..."...u...b...u...n...t...u...-...l...a...t...e...s...t...-...8...-...c...o...r...e..."...
... ... ... ... ...c...p...u..._...c...o...r...e...s...:... ...8...
... ... ... ... ...m...e...m...o...r...y..._...g...b...:... ...3...2...
... ... ... ... ...m...a...x..._...t...i...m...e...o...u...t...:... ...4...5...
... ... ... ... ...s...u...i...t...a...b...l...e..._...f...o...r...:...
... ... ... ... ... ... ...-... ..."...P...e...r...f...o...r...m...a...n...c...e... ...m...o...n...i...t...o...r...i...n...g..."...
... ... ... ... ... ... ...-... ..."...L...a...r...g...e...-...s...c...a...l...e... ...s...e...c...u...r...i...t...y... ...s...c...a...n...s..."...
... ... ... ... ... ... ...-... ..."...C...o...m...p...l...e...x... ...a...r...c...h...i...t...e...c...t...u...r...a...l... ...a...n...a...l...y...s...i...s..."...
...
...#... ...M...e...m...o...r...y... ...O...p...t...i...m...i...z...a...t...i...o...n... ...S...e...t...t...i...n...g...s...
...m...e...m...o...r...y...:...
... ... ...c...a...c...h...e..._...l...i...m...i...t...s...:...
... ... ... ... ...f...i...l...e..._...c...o...n...t...e...n...t..._...c...a...c...h...e...:... ..."...5...0...M...B..."...
... ... ... ... ...a...s...t..._...c...a...c...h...e...:... ..."...2...5...M...B..."...
... ... ... ... ...a...n...a...l...y...s...i...s..._...c...a...c...h...e...:... ..."...3...0...M...B..."...
... ... ...
... ... ...o...p...t...i...m...i...z...a...t...i...o...n..._...s...t...r...a...t...e...g...i...e...s...:...
... ... ... ... ...-... ..."...S...t...r...e...a...m...i...n...g... ...a...n...a...l...y...s...i...s... ...f...o...r... ...l...a...r...g...e... ...f...i...l...e...s..."...
... ... ... ... ...-... ..."...I...n...c...r...e...m...e...n...t...a...l... ...p...r...o...c...e...s...s...i...n...g... ...w...i...t...h... ...c...h...e...c...k...p...o...i...n...t...s..."...
... ... ... ... ...-... ..."...M...e...m...o...r...y...-...b...o...u...n...d...e...d... ...o...p...e...r...a...t...i...o...n...s... ...(...N...A...S...A... ...R...u...l...e... ...7...)..."...
... ... ... ... ...-... ..."...L...a...z...y... ...l...o...a...d...i...n...g... ...o...f... ...a...n...a...l...y...z...e...r... ...c...o...m...p...o...n...e...n...t...s..."...
... ... ...
... ... ...m...o...n...i...t...o...r...i...n...g...:...
... ... ... ... ...m...e...m...o...r...y..._...t...h...r...e...s...h...o...l...d...:... ..."...8...0...%..."...
... ... ... ... ...g...c..._...f...r...e...q...u...e...n...c...y...:... ..."...e...v...e...r...y..._...m...a...j...o...r..._...o...p...e...r...a...t...i...o...n..."...
... ... ... ... ...m...e...m...o...r...y..._...p...r...o...f...i...l...i...n...g...:... ...t...r...u...e...
...
...#... ...P...a...r...a...l...l...e...l... ...E...x...e...c...u...t...i...o...n... ...S...t...r...a...t...e...g...y...
...p...a...r...a...l...l...e...l..._...e...x...e...c...u...t...i...o...n...:...
... ... ...m...a...x..._...c...o...n...c...u...r...r...e...n...t..._...a...n...a...l...y...s...e...s...:... ...6...
... ... ...f...a...i...l..._...f...a...s...t...:... ...f...a...l...s...e...
... ... ...t...i...m...e...o...u...t..._...s...t...r...a...t...e...g...y...:... ..."...i...n...d...i...v...i...d...u...a...l..."...
... ... ...
... ... ...p...r...i...o...r...i...t...y..._...m...a...p...p...i...n...g...:...
... ... ... ... ...c...r...i...t...i...c...a...l...:... ...[..."...c...o...n...n...a...s...c...e...n...c...e..."...,... ..."...a...r...c...h...i...t...e...c...t...u...r...e..."...]...
... ... ... ... ...h...i...g...h...:... ...[..."...p...e...r...f...o...r...m...a...n...c...e..."...,... ..."...s...e...c...u...r...i...t...y..."...]...
... ... ... ... ...m...e...d...i...u...m...:... ...[..."...m...e...c...e..."...,... ..."...c...a...c...h...e..."...]...
... ... ... ... ...l...o...w...:... ...[..."...d...o...g...f...o...o...d...i...n...g..."...,... ..."...v...a...l...i...d...a...t...i...o...n..."...]...
...
...#... ...P...e...r...f...o...r...m...a...n...c...e... ...T...a...r...g...e...t...s... ...(...P...h...a...s...e... ...2...A... ...G...o...a...l...s...)...
...t...a...r...g...e...t...s...:...
... ... ...e...x...e...c...u...t...i...o...n..._...t...i...m...e..._...r...e...d...u...c...t...i...o...n...:... ..."...4...0...-...6...0...%..."...
... ... ...b...a...s...e...l...i...n...e..._...s...e...q...u...e...n...t...i...a...l..._...t...i...m...e...:... ..."...9...0... ...m...i...n...u...t...e...s..."...
... ... ...t...a...r...g...e...t..._...p...a...r...a...l...l...e...l..._...t...i...m...e...:... ..."...4...5...-...6...0... ...m...i...n...u...t...e...s..."...
... ... ...
... ... ...r...e...s...o...u...r...c...e..._...e...f...f...i...c...i...e...n...c...y...:...
... ... ... ... ...c...p...u..._...u...t...i...l...i...z...a...t...i...o...n...:... ..."...>...7...5...%..."...
... ... ... ... ...m...e...m...o...r...y..._...e...f...f...i...c...i...e...n...c...y...:... ..."...>...8...0...%..."...
... ... ... ... ...r...u...n...n...e...r..._...c...o...s...t..._...o...p...t...i...m...i...z...a...t...i...o...n...:... ..."...3...0...-...4...0...%..."...
...
...#... ...Q...u...a...l...i...t...y... ...G...a...t...e... ...I...n...t...e...g...r...a...t...i...o...n...
...q...u...a...l...i...t...y..._...g...a...t...e...s...:...
... ... ...p...e...r...f...o...r...m...a...n...c...e..._...t...h...r...e...s...h...o...l...d...s...:...
... ... ... ... ...m...i...n..._...c...p...u..._...e...f...f...i...c...i...e...n...c...y...:... ...0.......7...0...
... ... ... ... ...m...i...n..._...m...e...m...o...r...y..._...o...p...t...i...m...i...z...a...t...i...o...n...:... ...0.......6...5...
... ... ... ... ...m...a...x..._...e...x...e...c...u...t...i...o...n..._...t...i...m...e...:... ...6...0...
... ... ... ... ...
... ... ...f...a...i...l...u...r...e..._...h...a...n...d...l...i...n...g...:...
... ... ... ... ...r...e...t...r...y..._...s...t...r...a...t...e...g...y...:... ..."...i...m...m...e...d...i...a...t...e..._...o...n...c...e..."...
... ... ... ... ...f...a...l...l...b...a...c...k..._...m...o...d...e...:... ..."...s...e...q...u...e...n...t...i...a...l..._...c...r...i...t...i...c...a...l..._...o...n...l...y..."...
... ... ... ... ...n...o...t...i...f...i...c...a...t...i...o...n..._...t...h...r...e...s...h...o...l...d...:... ..."...2..._...f...a...i...l...u...r...e...s..."...