...#... ...S...e...c...u...r...i...t...y... ...H...a...r...d...e...n...i...n...g... ...C...o...n...f...i...g...u...r...a...t...i...o...n...
...#... ...P...h...a...s...e... ...2...B...:... ...S...t...a...n...d...a...r...d...i...z...e...d... ...S...e...c...u...r...i...t...y... ...P...i...p...e...l...i...n...e... ...I...n...t...e...g...r...a...t...i...o...n...
...
...#... ...S...e...c...u...r...i...t...y... ...A...n...a...l...y...s...i...s... ...M...a...t...r...i...x...
...s...e...c...u...r...i...t...y..._...a...n...a...l...y...s...e...s...:...
... ... ...s...a...s...t...:...
... ... ... ... ...n...a...m...e...:... ..."...S...t...a...t...i...c... ...A...p...p...l...i...c...a...t...i...o...n... ...S...e...c...u...r...i...t...y... ...T...e...s...t...i...n...g..."...
... ... ... ... ...r...u...n...n...e...r...:... ..."...u...b...u...n...t...u...-...l...a...t...e...s...t...-...4...-...c...o...r...e..."...
... ... ... ... ...t...i...m...e...o...u...t...:... ...3...0...
... ... ... ... ...t...o...o...l...s...:...
... ... ... ... ... ... ...-... ..."...b...a...n...d...i...t..."...
... ... ... ... ... ... ...-... ..."...s...e...m...g...r...e...p..."... ...
... ... ... ... ... ... ...-... ..."...c...o...d...e...q...l..."...
... ... ... ... ...s...e...v...e...r...i...t...y..._...l...e...v...e...l...s...:... ...[..."...c...r...i...t...i...c...a...l..."...,... ..."...h...i...g...h..."...,... ..."...m...e...d...i...u...m..."...,... ..."...l...o...w..."...]...
... ... ... ... ...
... ... ...s...u...p...p...l...y..._...c...h...a...i...n...:...
... ... ... ... ...n...a...m...e...:... ..."...S...u...p...p...l...y... ...C...h...a...i...n... ...S...e...c...u...r...i...t...y..."...
... ... ... ... ...r...u...n...n...e...r...:... ..."...u...b...u...n...t...u...-...l...a...t...e...s...t..."...
... ... ... ... ...t...i...m...e...o...u...t...:... ...2...0...
... ... ... ... ...t...o...o...l...s...:...
... ... ... ... ... ... ...-... ..."...s...a...f...e...t...y..."...
... ... ... ... ... ... ...-... ..."...p...i...p...-...a...u...d...i...t..."...
... ... ... ... ... ... ...-... ..."...d...e...p...e...n...d...e...n...c...y...-...c...h...e...c...k..."...
... ... ... ... ...f...o...c...u...s..._...a...r...e...a...s...:...
... ... ... ... ... ... ...-... ..."...d...e...p...e...n...d...e...n...c...y..._...v...u...l...n...e...r...a...b...i...l...i...t...i...e...s..."...
... ... ... ... ... ... ...-... ..."...l...i...c...e...n...s...e..._...c...o...m...p...l...i...a...n...c...e..."...
... ... ... ... ... ... ...-... ..."...o...u...t...d...a...t...e...d..._...p...a...c...k...a...g...e...s..."...
... ... ...
... ... ...s...e...c...r...e...t...s..._...d...e...t...e...c...t...i...o...n...:...
... ... ... ... ...n...a...m...e...:... ..."...S...e...c...r...e...t...s... ...D...e...t...e...c...t...i...o...n..."...
... ... ... ... ...r...u...n...n...e...r...:... ..."...u...b...u...n...t...u...-...l...a...t...e...s...t..."...
... ... ... ... ...t...i...m...e...o...u...t...:... ...1...5...
... ... ... ... ...t...o...o...l...s...:...
... ... ... ... ... ... ...-... ..."...t...r...u...f...f...l...e...H...o...g..."...
... ... ... ... ... ... ...-... ..."...d...e...t...e...c...t...-...s...e...c...r...e...t...s..."...
... ... ... ... ... ... ...-... ..."...g...i...t...l...e...a...k...s..."...
... ... ... ... ...s...c...a...n..._...s...c...o...p...e...:... ...[..."...c...o...d...e..."...,... ..."...h...i...s...t...o...r...y..."...,... ..."...c...o...n...f...i...g..."...]...
...
...#... ...S...e...c...u...r...i...t...y... ...Q...u...a...l...i...t...y... ...G...a...t...e...s...
...q...u...a...l...i...t...y..._...g...a...t...e...s...:...
... ... ...c...r...i...t...i...c...a...l..._...f...i...n...d...i...n...g...s...:...
... ... ... ... ...m...a...x..._...a...l...l...o...w...e...d...:... ...0...
... ... ... ... ...b...l...o...c...k..._...d...e...p...l...o...y...m...e...n...t...:... ...t...r...u...e...
... ... ... ... ...n...o...t...i...f...i...c...a...t...i...o...n...:... ..."...i...m...m...e...d...i...a...t...e..."...
... ... ... ... ...
... ... ...h...i...g...h..._...f...i...n...d...i...n...g...s...:...
... ... ... ... ...m...a...x..._...a...l...l...o...w...e...d...:... ...3...
... ... ... ... ...b...l...o...c...k..._...d...e...p...l...o...y...m...e...n...t...:... ...t...r...u...e...
... ... ... ... ...n...o...t...i...f...i...c...a...t...i...o...n...:... ..."...i...m...m...e...d...i...a...t...e..."...
... ... ... ... ...
... ... ...m...e...d...i...u...m..._...f...i...n...d...i...n...g...s...:...
... ... ... ... ...m...a...x..._...a...l...l...o...w...e...d...:... ...1...0...
... ... ... ... ...b...l...o...c...k..._...d...e...p...l...o...y...m...e...n...t...:... ...f...a...l...s...e...
... ... ... ... ...n...o...t...i...f...i...c...a...t...i...o...n...:... ..."...d...a...i...l...y..._...d...i...g...e...s...t..."...
... ... ... ... ...
... ... ...d...e...p...e...n...d...e...n...c...y..._...a...g...e...:...
... ... ... ... ...m...a...x..._...d...a...y...s..._...b...e...h...i...n...d...:... ...9...0...
... ... ... ... ...b...l...o...c...k..._...d...e...p...l...o...y...m...e...n...t...:... ...f...a...l...s...e...
... ... ... ... ...n...o...t...i...f...i...c...a...t...i...o...n...:... ..."...w...e...e...k...l...y..."...
...
...#... ...N...A...S...A... ...P...O...T...1...0... ...S...e...c...u...r...i...t...y... ...C...o...m...p...l...i...a...n...c...e...
...n...a...s...a..._...c...o...m...p...l...i...a...n...c...e...:...
... ... ...r...u...l...e..._...3..._...a...s...s...e...r...t...i...o...n...s...:... ...
... ... ... ... ...e...n...a...b...l...e...d...:... ...t...r...u...e...
... ... ... ... ...m...i...n..._...c...o...v...e...r...a...g...e...:... ..."...9...0...%..."...
... ... ... ... ...
... ... ...r...u...l...e..._...7..._...m...e...m...o...r...y..._...b...o...u...n...d...s...:...
... ... ... ... ...e...n...a...b...l...e...d...:... ...t...r...u...e...
... ... ... ... ...m...a...x..._...m...e...m...o...r...y..._...u...s...a...g...e...:... ..."...8...0...%..."...
... ... ... ... ...
... ... ...r...u...l...e..._...8..._...e...r...r...o...r..._...h...a...n...d...l...i...n...g...:...
... ... ... ... ...e...n...a...b...l...e...d...:... ...t...r...u...e...
... ... ... ... ...u...n...c...a...u...g...h...t..._...e...x...c...e...p...t...i...o...n...s...:... ...0...
... ... ... ... ...
... ... ...r...u...l...e..._...9..._...l...o...o...p..._...b...o...u...n...d...s...:...
... ... ... ... ...e...n...a...b...l...e...d...:... ...t...r...u...e...
... ... ... ... ...m...a...x..._...i...t...e...r...a...t...i...o...n...s...:... ...1...0...0...0...0...
... ... ... ... ...
... ... ...r...u...l...e..._...1...0..._...f...u...n...c...t...i...o...n..._...s...i...z...e...:...
... ... ... ... ...e...n...a...b...l...e...d...:... ...t...r...u...e...
... ... ... ... ...m...a...x..._...l...i...n...e...s...:... ...6...0...
... ... ... ... ...m...a...x..._...s...t...a...t...e...m...e...n...t...s...:... ...5...0...
...
...#... ...S...e...c...u...r...i...t...y... ...P...i...p...e...l...i...n...e... ...I...n...t...e...g...r...a...t...i...o...n...
...p...i...p...e...l...i...n...e..._...s...t...a...g...e...s...:...
... ... ...p...r...e..._...a...n...a...l...y...s...i...s...:...
... ... ... ... ...-... ..."...d...e...p...e...n...d...e...n...c...y..._...i...n...s...t...a...l...l...a...t...i...o...n..."...
... ... ... ... ...-... ..."...e...n...v...i...r...o...n...m...e...n...t..._...v...a...l...i...d...a...t...i...o...n..."... ...
... ... ... ... ...-... ..."...s...e...c...u...r...i...t...y..._...t...o...o...l..._...s...e...t...u...p..."...
... ... ... ... ...
... ... ...a...n...a...l...y...s...i...s...:...
... ... ... ... ...-... ..."...s...a...s...t..._...s...c...a...n...n...i...n...g..."...
... ... ... ... ...-... ..."...d...e...p...e...n...d...e...n...c...y..._...s...c...a...n...n...i...n...g..."...
... ... ... ... ...-... ..."...s...e...c...r...e...t...s..._...d...e...t...e...c...t...i...o...n..."...
... ... ... ... ...-... ..."...l...i...c...e...n...s...e..._...c...o...m...p...l...i...a...n...c...e..."...
... ... ... ... ...
... ... ...p...o...s...t..._...a...n...a...l...y...s...i...s...:...
... ... ... ... ...-... ..."...v...u...l...n...e...r...a...b...i...l...i...t...y..._...a...s...s...e...s...s...m...e...n...t..."...
... ... ... ... ...-... ..."...c...o...m...p...l...i...a...n...c...e..._...v...a...l...i...d...a...t...i...o...n..."...
... ... ... ... ...-... ..."...s...e...c...u...r...i...t...y..._...g...a...t...e..._...e...v...a...l...u...a...t...i...o...n..."...
... ... ... ... ...-... ..."...a...r...t...i...f...a...c...t..._...g...e...n...e...r...a...t...i...o...n..."...
...
...#... ...N...o...t...i...f...i...c...a...t...i...o...n... ...a...n...d... ...R...e...p...o...r...t...i...n...g...
...n...o...t...i...f...i...c...a...t...i...o...n...s...:...
... ... ...s...e...c...u...r...i...t...y..._...t...e...a...m...:...
... ... ... ... ...c...r...i...t...i...c...a...l..._...f...i...n...d...i...n...g...s...:... ..."...s...l...a...c...k..._...i...m...m...e...d...i...a...t...e..."...
... ... ... ... ...c...o...m...p...l...i...a...n...c...e..._...f...a...i...l...u...r...e...s...:... ..."...e...m...a...i...l..._...i...m...m...e...d...i...a...t...e..."...
... ... ... ... ...
... ... ...d...e...v...e...l...o...p...m...e...n...t..._...t...e...a...m...:...
... ... ... ... ...h...i...g...h..._...f...i...n...d...i...n...g...s...:... ..."...g...i...t...h...u...b..._...p...r..._...c...o...m...m...e...n...t..."...
... ... ... ... ...g...a...t...e..._...f...a...i...l...u...r...e...s...:... ..."...g...i...t...h...u...b..._...i...s...s...u...e..."...
... ... ... ... ...
... ... ...m...a...n...a...g...e...m...e...n...t...:...
... ... ... ... ...w...e...e...k...l...y..._...s...u...m...m...a...r...y...:... ..."...e...m...a...i...l..._...d...i...g...e...s...t..."...
... ... ... ... ...c...o...m...p...l...i...a...n...c...e..._...s...t...a...t...u...s...:... ..."...d...a...s...h...b...o...a...r...d..._...u...p...d...a...t...e..."...
...
...#... ...I...n...t...e...g...r...a...t...i...o...n... ...P...o...i...n...t...s...
...i...n...t...e...g...r...a...t...i...o...n...s...:...
... ... ...g...i...t...h...u...b..._...s...e...c...u...r...i...t...y...:...
... ... ... ... ...e...n...a...b...l...e..._...d...e...p...e...n...d...e...n...c...y..._...a...l...e...r...t...s...:... ...t...r...u...e...
... ... ... ... ...e...n...a...b...l...e..._...c...o...d...e..._...s...c...a...n...n...i...n...g...:... ...t...r...u...e...
... ... ... ... ...e...n...a...b...l...e..._...s...e...c...r...e...t..._...s...c...a...n...n...i...n...g...:... ...t...r...u...e...
... ... ... ... ...
... ... ...e...x...t...e...r...n...a...l..._...t...o...o...l...s...:...
... ... ... ... ...s...o...n...a...r...q...u...b...e..._...i...n...t...e...g...r...a...t...i...o...n...:... ...f...a...l...s...e...
... ... ... ... ...s...n...y...k..._...i...n...t...e...g...r...a...t...i...o...n...:... ...f...a...l...s...e...
... ... ... ... ...c...u...s...t...o...m..._...s...c...a...n...n...e...r...s...:... ...[...]...