// QualityDashboard Facade - FSM Range 800-899
// Generated by Range-Based Eliminator

import { QualityDashboardCore } from './QualityDashboardCore';
import { QualityDashboardStateMachine } from './QualityDashboardStateMachine';

export class QualityDashboardFacade {
    private core: QualityDashboardCore;
    private fsm: QualityDashboardStateMachine;

    constructor() {
        this.core = new QualityDashboardCore();
        this.fsm = new QualityDashboardStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility
export default QualityDashboardFacade;
