// QualityDashboard Types - FSM Range 800-899
// Generated by Range-Based Eliminator

export interface DashboardMetrics {
overall: OverallMetrics;
sixSigma: SixSigmaMetrics;
nasa: NASAMetrics;
performance: PerformanceMetrics;
security: SecurityMetrics;
gates: GateMetrics;
trends: TrendMetrics;
}
export interface OverallMetrics {
qualityScore: number; // 0-100
status: 'excellent' | 'good' | 'warning' | 'critical';
lastUpdated: Date;
environment: string;
version: string;
}
export interface SixSigmaMetrics {
currentLevel: number; // 1-6
defectRate: number; // PPM
processCapability: number;
qualityScore: number;
trend: 'improving' | 'stable' | 'declining';
}



// Range-specific type definitions for 800-899
export interface QualityDashboardConfig {
    range: '800-899';
    maxLines: number;
    decomposed: boolean;
}
