// GitHubProjectIntegration Facade - FSM Range 700-799
// Generated by Range-Based Eliminator

import { GitHubProjectIntegrationCore } from './GitHubProjectIntegrationCore';
import { GitHubProjectIntegrationStateMachine } from './GitHubProjectIntegrationStateMachine';

export class GitHubProjectIntegrationFacade {
    private core: GitHubProjectIntegrationCore;
    private fsm: GitHubProjectIntegrationStateMachine;

    constructor() {
        this.core = new GitHubProjectIntegrationCore();
        this.fsm = new GitHubProjectIntegrationStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility
export default GitHubProjectIntegrationFacade;
