// TemplateGenerator State Machine - FSM Range 600-699
// Generated by Range-Based Eliminator

export enum TemplateGeneratorEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface TemplateGeneratorState {
    name: string;
    data?: any;
}

export class TemplateGeneratorStateMachine {
    private currentState: TemplateGeneratorState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: TemplateGeneratorEvents, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === TemplateGeneratorEvents.START) {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === TemplateGeneratorEvents.COMPLETE) {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): TemplateGeneratorState {
        return this.currentState;
    }
}
