// TemplateGenerator Types - FSM Range 600-699
// Generated by Range-Based Eliminator





// Range-specific type definitions for 600-699
export interface TemplateGeneratorConfig {
    range: '600-699';
    maxLines: number;
    decomposed: boolean;
}
