# Semgrep configuration overlay for SPEK template
# Extends p/owasp-top-ten with custom rules

rules:
  # Custom rule: Detect hardcoded secrets in config files
  - id: hardcoded-secret-in-config
    patterns:
      - pattern: |
          $KEY = "$VALUE"
      - metavariable-regex:
          metavariable: $KEY
          regex: (?i)(api[_-]?key|secret|token|password|auth)
      - metavariable-regex:
          metavariable: $VALUE
          regex: ^[A-Za-z0-9+/]{16,}={0,2}$
    message: Potential hardcoded secret detected
    languages: [yaml, json, javascript, typescript]
    severity: ERROR
    
  # Custom rule: Unsafe eval-like functions
  - id: unsafe-eval-usage
    patterns:
      - pattern: eval($ARG)
      - pattern: Function($ARG)
      - pattern: new Function($ARG)
      - pattern: setTimeout($STRING, ...)
      - pattern: setInterval($STRING, ...)
    message: Unsafe eval-like function usage detected
    languages: [javascript, typescript]
    severity: ERROR
    
  # Custom rule: Missing input validation
  - id: missing-input-validation
    patterns:
      - pattern: |
          function $FUNC($PARAM) {
            ...
            $PARAM.$METHOD(...)
            ...
          }
      - pattern-not: |
          function $FUNC($PARAM) {
            ...
            if (...) { ... }
            ...
            $PARAM.$METHOD(...)
            ...
          }
    message: Potential missing input validation
    languages: [javascript, typescript]
    severity: WARNING
    
  # Custom rule: Insecure random number generation
  - id: weak-random
    patterns:
      - pattern: Math.random()
    message: Use cryptographically secure random number generation for security purposes
    languages: [javascript, typescript]
    severity: WARNING
    fix: crypto.randomBytes(4).readUInt32BE(0) / 0x100000000