// QueenDecisionEngine Facade - FSM Range 800-899
// Generated by Range-Based Eliminator

import { QueenDecisionEngineCore } from './QueenDecisionEngineCore';
import { QueenDecisionEngineStateMachine } from './QueenDecisionEngineStateMachine';

export class QueenDecisionEngineFacade {
    private core: QueenDecisionEngineCore;
    private fsm: QueenDecisionEngineStateMachine;

    constructor() {
        this.core = new QueenDecisionEngineCore();
        this.fsm = new QueenDecisionEngineStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility

// Backward compatibility

// Backward compatibility
export default QueenDecisionEngineFacade;
