/**
 * Type definitions for CICDWorkflowEngine
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */

import { Timestamp, Milliseconds } from '~types/base/primitives';

export interface ExecutionMetrics {
  count: number;
  duration: Milliseconds;
  successRate: number;
  timestamp: Timestamp;
}

export interface WorkflowArtifact {
  value: unknown;
}

export interface WorkflowConfig {
  enabled: boolean;
  timeout: Milliseconds;
  retries: number;
  maxConcurrency: number;
}

export interface WorkflowStep {
  value: unknown;
}

/* AGENT FOOTER BEGIN: DO NOT EDIT ABOVE THIS LINE */
/*
 * Version & Run Log
 * Version | Timestamp | Agent/Model | Change Summary | Artifacts | Status | Notes | Cost | Hash
 * 1.0.0 | 2025-09-30T12:55:14.358298 | AutoTypeGen@Phase3 | Generated 4 type exports | ./cicd/CICDWorkflowEngine.ts | OK | Automated generation | 0.00 | 9a79d88
 *
 * Receipt:
 * - status: OK
 * - reason_if_blocked: --
 * - run_id: auto-type-gen-9a79d88
 * - inputs: ["./cicd/CICDWorkflowEngine"]
 * - tools_used: ["TypeInference", "TypeGenerator"]
 * - versions: {"script":"1.0.0","nasa_rule_10":"compliant","fsm":"enum-based"}
 */
/* AGENT FOOTER END: DO NOT EDIT BELOW THIS LINE */
