/**
 * Type definitions for CICDDeploymentManager
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */

import { Timestamp, Milliseconds } from '~types/base/primitives';

export interface DeploymentStrategy {
  value: unknown;
}

export interface EnvironmentConfig {
  enabled: boolean;
  timeout: Milliseconds;
  retries: number;
  maxConcurrency: number;
}

export interface HealthCheck {
  value: unknown;
}

export enum RollbackTrigger {
  INITIALIZE = 'INITIALIZE',
  START = 'START',
  UPDATE = 'UPDATE',
  VALIDATE = 'VALIDATE',
  COMPLETE = 'COMPLETE',
  ERROR = 'ERROR'
}

/* AGENT FOOTER BEGIN: DO NOT EDIT ABOVE THIS LINE */
/*
 * Version & Run Log
 * Version | Timestamp | Agent/Model | Change Summary | Artifacts | Status | Notes | Cost | Hash
 * 1.0.0 | 2025-09-30T12:55:14.359295 | AutoTypeGen@Phase3 | Generated 4 type exports | ./cicd/CICDDeploymentManager.ts | OK | Automated generation | 0.00 | 45d55f0
 *
 * Receipt:
 * - status: OK
 * - reason_if_blocked: --
 * - run_id: auto-type-gen-45d55f0
 * - inputs: ["./cicd/CICDDeploymentManager"]
 * - tools_used: ["TypeInference", "TypeGenerator"]
 * - versions: {"script":"1.0.0","nasa_rule_10":"compliant","fsm":"enum-based"}
 */
/* AGENT FOOTER END: DO NOT EDIT BELOW THIS LINE */
