// CPUProfiler State Machine - FSM Range 700-799
// Generated by Range-Based Eliminator

export enum CPUProfilerEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface CPUProfilerState {
    name: string;
    data?: any;
}

export class CPUProfilerStateMachine {
    private currentState: CPUProfilerState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: CPUProfilerEvents, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === CPUProfilerEvents.START) {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === CPUProfilerEvents.COMPLETE) {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): CPUProfilerState {
        return this.currentState;
    }
}
