// CPUProfiler Facade - FSM Range 700-799
// Generated by Range-Based Eliminator

// TODO(Phase 4): Implement core module - import { CPUProfilerCore } from './CPUProfilerCore';
import { CPUProfilerStateMachine } from './CPUProfilerStateMachine';

export class CPUProfilerFacade {
    private core: CPUProfilerCore;
    private fsm: CPUProfilerStateMachine;

    constructor() {
        this.core = new CPUProfilerCore();
        this.fsm = new CPUProfilerStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility

// Backward compatibility

// Backward compatibility
export default CPUProfilerFacade;
