// CPUProfiler Types - FSM Range 700-799
// Generated by Range-Based Eliminator

export interface CPUProfile {
startTime: number;
endTime: number;
duration: number;
samples: CPUSample[];
aggregatedStats: CPUStats;
hotspots: CPUHotspot[];
functions: FunctionProfile[];
callTree: CallTreeNode;
analysis: CPUAnalysis;
}
export interface CPUSample {
timestamp: number;
cpuUsage: NodeJS.CpuUsage;
percentage: number;
loadAverage: number[];
activeHandles: number;
activeRequests: number;
stackTrace?: string[];
}
export interface CPUStats {
averageUsage: number;
peakUsage: number;
userTime: number;
systemTime: number;
totalTime: number;
utilizationRate: number; // 0-1
efficiency: number; // 0-1
samples: number;
}



// Range-specific type definitions for 700-799
export interface CPUProfilerConfig {
    range: '700-799';
    maxLines: number;
    decomposed: boolean;
}
