/**
 * Type definitions for CICDQualityGateManager
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */

import { Timestamp, Milliseconds } from '~types/base/primitives';

export interface ApprovalGate {
  value: unknown;
}

export interface CICDQualityGateManager {
  value: unknown;
}

export interface QualityGateIntegration {
  value: unknown;
}

export interface QualityGateResult {
  success: boolean;
  data: unknown;
  error: string | undefined;
  timestamp: Timestamp;
}

/* AGENT FOOTER BEGIN: DO NOT EDIT ABOVE THIS LINE */
/*
 * Version & Run Log
 * Version | Timestamp | Agent/Model | Change Summary | Artifacts | Status | Notes | Cost | Hash
 * 1.0.0 | 2025-09-30T12:55:14.357301 | AutoTypeGen@Phase3 | Generated 4 type exports | ./CICDQualityGateManager.ts | OK | Automated generation | 0.00 | 93d3604
 *
 * Receipt:
 * - status: OK
 * - reason_if_blocked: --
 * - run_id: auto-type-gen-93d3604
 * - inputs: ["./CICDQualityGateManager"]
 * - tools_used: ["TypeInference", "TypeGenerator"]
 * - versions: {"script":"1.0.0","nasa_rule_10":"compliant","fsm":"enum-based"}
 */
/* AGENT FOOTER END: DO NOT EDIT BELOW THIS LINE */
