/**
 * Type definitions for KellyCriterionEngine
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */

import { Timestamp, Milliseconds } from '../types/base/primitives';

export interface KellyPortfolio {
  value: unknown;
}

export interface KellyPosition {
  value: unknown;
}

export interface MarketOpportunity {
  value: unknown;
}

/* AGENT FOOTER BEGIN: DO NOT EDIT ABOVE THIS LINE */
/*
 * Version & Run Log
 * Version | Timestamp | Agent/Model | Change Summary | Artifacts | Status | Notes | Cost | Hash
 * 1.0.0 | 2025-09-30T12:55:14.369269 | AutoTypeGen@Phase3 | Generated 3 type exports | ./KellyCriterionEngine.ts | OK | Automated generation | 0.00 | 5c19689
 *
 * Receipt:
 * - status: OK
 * - reason_if_blocked: --
 * - run_id: auto-type-gen-5c19689
 * - inputs: ["./KellyCriterionEngine"]
 * - tools_used: ["TypeInference", "TypeGenerator"]
 * - versions: {"script":"1.0.0","nasa_rule_10":"compliant","fsm":"enum-based"}
 */
/* AGENT FOOTER END: DO NOT EDIT BELOW THIS LINE */
