/**
 * Type definitions for PhaseTransitionMonitor
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */

import { Timestamp, Milliseconds } from '../types/base/primitives';

export interface PhaseExecutionMonitor {
  value: unknown;
}

export interface PhasePerformanceSummary {
  value: unknown;
}

export interface SystemMetrics {
  count: number;
  duration: Milliseconds;
  successRate: number;
  timestamp: Timestamp;
}

export interface SystemMetricsMonitor {
  value: unknown;
}

export interface TransitionExecutionMonitor {
  value: unknown;
}

export interface TransitionPerformanceSummary {
  value: unknown;
}

/* AGENT FOOTER BEGIN: DO NOT EDIT ABOVE THIS LINE */
/*
 * Version & Run Log
 * Version | Timestamp | Agent/Model | Change Summary | Artifacts | Status | Notes | Cost | Hash
 * 1.0.0 | 2025-09-30T12:55:14.351318 | AutoTypeGen@Phase3 | Generated 6 type exports | ./PhaseTransitionMonitor.ts | OK | Automated generation | 0.00 | e91415b
 *
 * Receipt:
 * - status: OK
 * - reason_if_blocked: --
 * - run_id: auto-type-gen-e91415b
 * - inputs: ["./PhaseTransitionMonitor"]
 * - tools_used: ["TypeInference", "TypeGenerator"]
 * - versions: {"script":"1.0.0","nasa_rule_10":"compliant","fsm":"enum-based"}
 */
/* AGENT FOOTER END: DO NOT EDIT BELOW THIS LINE */
