/**
 * Type definitions for QueenDebugTypes
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */

import { Timestamp, Milliseconds } from '../types/base/primitives';

export interface AuditValidatorResult {
  success: boolean;
  data: unknown;
  error: string | undefined;
  timestamp: Timestamp;
}

export interface DebugExecutionResult {
  success: boolean;
  data: unknown;
  error: string | undefined;
  timestamp: Timestamp;
}

export interface DebugMetrics {
  count: number;
  duration: Milliseconds;
  successRate: number;
  timestamp: Timestamp;
}

export interface DebugProgress {
  value: unknown;
}

export interface TheaterEvidence {
  value: unknown;
}

/* AGENT FOOTER BEGIN: DO NOT EDIT ABOVE THIS LINE */
/*
 * Version & Run Log
 * Version | Timestamp | Agent/Model | Change Summary | Artifacts | Status | Notes | Cost | Hash
 * 1.0.0 | 2025-09-30T12:55:14.352315 | AutoTypeGen@Phase3 | Generated 5 type exports | ./QueenDebugTypes.ts | OK | Automated generation | 0.00 | 0014273
 *
 * Receipt:
 * - status: OK
 * - reason_if_blocked: --
 * - run_id: auto-type-gen-0014273
 * - inputs: ["./QueenDebugTypes"]
 * - tools_used: ["TypeInference", "TypeGenerator"]
 * - versions: {"script":"1.0.0","nasa_rule_10":"compliant","fsm":"enum-based"}
 */
/* AGENT FOOTER END: DO NOT EDIT BELOW THIS LINE */
