/**
 * Type definitions for RiskMonitoringDashboard
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */

import { Timestamp, Milliseconds } from '../types/base/primitives';

export interface AlertConfiguration {
  value: unknown;
}

export enum DashboardState {
  IDLE = 'IDLE',
  INITIALIZING = 'INITIALIZING',
  ACTIVE = 'ACTIVE',
  PROCESSING = 'PROCESSING',
  VALIDATING = 'VALIDATING',
  COMPLETE = 'COMPLETE'
}

export interface ProbabilityOfRuin {
  value: unknown;
}

export interface RiskAlert {
  value: unknown;
}

export interface RiskMetrics {
  count: number;
  duration: Milliseconds;
  successRate: number;
  timestamp: Timestamp;
}

export interface RiskMonitoringDashboard {
  value: unknown;
}

/* AGENT FOOTER BEGIN: DO NOT EDIT ABOVE THIS LINE */
/*
 * Version & Run Log
 * Version | Timestamp | Agent/Model | Change Summary | Artifacts | Status | Notes | Cost | Hash
 * 1.0.0 | 2025-09-30T12:55:14.352315 | AutoTypeGen@Phase3 | Generated 6 type exports | ./RiskMonitoringDashboard.ts | OK | Automated generation | 0.00 | 9ae70d7
 *
 * Receipt:
 * - status: OK
 * - reason_if_blocked: --
 * - run_id: auto-type-gen-9ae70d7
 * - inputs: ["./RiskMonitoringDashboard"]
 * - tools_used: ["TypeInference", "TypeGenerator"]
 * - versions: {"script":"1.0.0","nasa_rule_10":"compliant","fsm":"enum-based"}
 */
/* AGENT FOOTER END: DO NOT EDIT BELOW THIS LINE */
