/**
 * Type definitions for WorkflowStateMachine
 * Generated by automated type generator
 * FSM-compliant with NASA Rule 10
 */

import { Timestamp, Milliseconds } from '~types/base/primitives';

export enum WorkflowEvent {
  INITIALIZE = 'INITIALIZE',
  START = 'START',
  UPDATE = 'UPDATE',
  VALIDATE = 'VALIDATE',
  COMPLETE = 'COMPLETE',
  ERROR = 'ERROR'
}

export enum WorkflowState {
  IDLE = 'IDLE',
  INITIALIZING = 'INITIALIZING',
  ACTIVE = 'ACTIVE',
  PROCESSING = 'PROCESSING',
  VALIDATING = 'VALIDATING',
  COMPLETE = 'COMPLETE'
}

/* AGENT FOOTER BEGIN: DO NOT EDIT ABOVE THIS LINE */
/*
 * Version & Run Log
 * Version | Timestamp | Agent/Model | Change Summary | Artifacts | Status | Notes | Cost | Hash
 * 1.0.0 | 2025-09-30T12:55:14.364283 | AutoTypeGen@Phase3 | Generated 3 type exports | ./WorkflowStateMachine.ts | OK | Automated generation | 0.00 | 3073274
 *
 * Receipt:
 * - status: OK
 * - reason_if_blocked: --
 * - run_id: auto-type-gen-3073274
 * - inputs: ["./WorkflowStateMachine"]
 * - tools_used: ["TypeInference", "TypeGenerator"]
 * - versions: {"script":"1.0.0","nasa_rule_10":"compliant","fsm":"enum-based"}
 */
/* AGENT FOOTER END: DO NOT EDIT BELOW THIS LINE */
