// PerformanceOverheadValidator Facade - FSM Range 800-899
// Generated by Range-Based Eliminator

import { PerformanceOverheadValidatorCore } from './PerformanceOverheadValidatorCore';
import { PerformanceOverheadValidatorStateMachine } from './PerformanceOverheadValidatorStateMachine';

export class PerformanceOverheadValidatorFacade {
    private core: PerformanceOverheadValidatorCore;
    private fsm: PerformanceOverheadValidatorStateMachine;

    constructor() {
        this.core = new PerformanceOverheadValidatorCore();
        this.fsm = new PerformanceOverheadValidatorStateMachine();
    }

    // Unified interface preserving original API
    async processRequest(request: any): Promise<any> {
        this.fsm.transition('START', request);
        const result = await this.core.process(request);
        this.fsm.transition('COMPLETE', result);
        return result;
    }
}

// Export original API compatibility
export default PerformanceOverheadValidatorFacade;
