// PerformanceOverheadValidator Types - FSM Range 800-899
// Generated by Range-Based Eliminator

export interface PerformanceOverheadConfig {
maxOverheadPercentage: number; // 0.4% default
measurementWindow: number; // milliseconds
baselineCollectionPeriod: number; // milliseconds
alertThreshold: number; // percentage
criticalThreshold: number; // percentage
enableContinuousMonitoring: boolean;
enableDetailedProfiling: boolean;
}
export interface PerformanceBaseline {
timestamp: Date;
duration: number; // baseline measurement period
metrics: BaselineMetrics;
environment: string;
conditions: Record<string, any>;
}
export interface BaselineMetrics {
cpuUsage: {
mean: number;
max: number;
p95: number;
};
memoryUsage: {
mean: number;
max: number;
p95: number;
};
responseTime: {
mean: number;
max: number;
p95: number;
};
throughput: {
requestsPerSecond: number;
operationsPerSecond: number;
};
networkLatency: {
mean: number;
max: number;
p95: number;
};
}



// Range-specific type definitions for 800-899
export interface PerformanceOverheadValidatorConfig {
    range: '800-899';
    maxLines: number;
    decomposed: boolean;
}
