// PerformanceOverheadValidator State Machine - FSM Range 800-899
// Generated by Range-Based Eliminator

export enum PerformanceOverheadValidatorEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface PerformanceOverheadValidatorState {
    name: string;
    data?: any;
}

export class PerformanceOverheadValidatorStateMachine {
    private currentState: PerformanceOverheadValidatorState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: PerformanceOverheadValidatorEvents, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === PerformanceOverheadValidatorEvents.START) {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === PerformanceOverheadValidatorEvents.COMPLETE) {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): PerformanceOverheadValidatorState {
        return this.currentState;
    }
}
