name: Architecture Analysis
on:
  push:
    branches: [main]
    paths:
      - 'analyzer/**'
      - 'src/**'
      - '**/*.py'
  pull_request:
    branches: [main]
    paths:
      - 'analyzer/**'
      - 'src/**'
      - '**/*.py'
  workflow_dispatch:
    inputs:
      trigger-reason:
        description: 'Reason for triggering analysis'
        required: false
        default: 'manual'

jobs:
  architecture-analysis:
    runs-on: ubuntu-latest
    name: "Architecture Analysis with Hotspots"
    timeout-minutes: 30
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        if [ -f setup.py ]; then
          pip install -e .
        fi

    - name: Create Artifacts Directory
      run: mkdir -p .claude/.artifacts

    - name: Architecture Analysis with Hotspot Detection
      run: |
        echo "Running architecture analysis with hotspot detection..."
        cd analyzer
        python ../.github/scripts/architecture_analysis.py

    - name: Architecture Health Assessment
      run: |
        if [ -f .claude/.artifacts/architecture_analysis.json ]; then
          echo "=== Architecture Analysis Summary ==="
          python .github/scripts/health_assessment.py
        else
          echo "[ERROR] Architecture analysis file not found"
          exit 1
        fi

    - name: Quality Gate Assessment
      run: |
        python .github/scripts/quality_gates.py

    - name: Upload Architecture Analysis Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: architecture-analysis-${{ github.run_number }}
        path: .claude/.artifacts/architecture_analysis.json
        retention-days: 30

    - name: Comment on PR with Analysis
      if: github.event_name == 'pull_request'
      run: |
        echo "PR comment creation would go here"
        echo "Analysis results available in artifacts"