// blue-green-engine Types - FSM Range 700-799
// Generated by Range-Based Eliminator





// Range-specific type definitions for 700-799
export interface blue-green-engineConfig {
    range: '700-799';
    maxLines: number;
    decomposed: boolean;
}
