// blue-green-engine State Machine - FSM Range 700-799
// Generated by Range-Based Eliminator

export enum blue-green-engineEvents {
    START = 'START',
    PROCESS = 'PROCESS',
    VALIDATE = 'VALIDATE',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR'
}

export interface blue-green-engineState {
    name: string;
    data?: any;
}

export class blue-green-engineStateMachine {
    private currentState: blue-green-engineState;

    constructor() {
        this.currentState = { name: 'initial' };
    }

    transition(event: blue-green-engineEvents, data?: any): void {
        switch (this.currentState.name) {
            case 'initial':
                if (event === blue-green-engineEvents.START) {
                    this.currentState = { name: 'processing', data };
                }
                break;
            case 'processing':
                if (event === blue-green-engineEvents.COMPLETE) {
                    this.currentState = { name: 'completed', data };
                }
                break;
        }
    }

    getState(): blue-green-engineState {
        return this.currentState;
    }
}
